version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: efc_frontend_prod:latest
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Si necesitas montar archivos estáticos personalizados, descomenta y ajusta:
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
