# Dockerfile de producción para Vite + React
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
COPY vite.config.* ./
RUN npm install --frozen-lockfile

COPY . .
RUN npm run build

# Etapa final: Nginx para servir archivos estáticos
FROM nginx:alpine

# Copia los archivos estáticos generados a la carpeta de Nginx
COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
